### ISSUE TITLE
Mic streaming

### ISSUE THREAD

**Issue by mahmoud-araby** [felixjunghans/google_speech#1]
I couldn`t find any mic streaming library compatible with the speech recognition streaming in your package if you can recommend a package please tell me, or if you can add one to the package that will be great

**Comment by felixjunghans** [comment]
Hi @mahmoud-araby, I will need exactly the same use case in the near future and try to provide an example in the package as soon as possible.

**Comment by felixjunghans** [comment]
I have just added a new sample project. It works with https://pub.dev/packages/sound_stream as this was the first package I could find. (Whether it is the best at the moment I can't judge). Personally, I'm waiting for flutter_sound to support streaming microphone input and I will use it from this moment on. But for now, my sample project shows that it is technically possible to transcribe directly from the microphone with google_speech and flutter.

I hope I could help you.

**Comment by mahmoud-araby** [comment]
Hi, @felixjunghans I thank you very much for your effort it did actually work but yes it`s not the best answer it takes speakers' output as input keeps repeating itself sometimes, I will be waiting for integrating flutter_sound with your package.

again thanks for your effort

**Comment by ddeewwaann** [comment]
sorry i want to ask, i have run in my project and got E/flutter (22918): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: gRPC Error (11, Audio Timeout Error: Long duration elapsed without audio. Audio should be sent close to real time.)
E/flutter (22918): null. Can you give me a solution ?

**Comment by felixjunghans** [comment]
Hi @ddeewwaann, this error usually occurs when no data is sent through the api. This can happen, for example, if an error occurs when reading data from a file. If you have tried to send data directly from a mic input, please check if data from the mic input reaches the api at all.  The error means that no data was sent to the Api, or it took too long before the data arrived at the Api.

**Comment by ddeewwaann** [comment]
> Hi @ddeewwaann, this error usually occurs when no data is sent through the api. This can happen, for example, if an error occurs when reading data from a file. If you have tried to send data directly from a mic input, please check if data from the mic input reaches the api at all.  The error means that no data was sent to the Api, or it took too long before the data arrived at the Api. 

when i tried using android virtual device it failed like that. I try to using real device and it works. Any suggestion or something? because im new in flutter

**Comment by felixjunghans** [comment]
I have not yet tested it with an Android emulator, but only with an iPhone simulator so far. Are you sure that you have set the microphone input on the emulator to on and data from the microphone is coming in? Because it sounds to me like there is no microphone data coming into the emulator.

**Comment by ddeewwaann** [comment]
> I have not yet tested it with an Android emulator, but only with an iPhone simulator so far. Are you sure that you have set the microphone input on the emulator to on and data from the microphone is coming in? Because it sounds to me like there is no microphone data coming into the emulator. 

yes i think so it because  microphone from the emulator. I have give the permission on the AVD and test my microphone laptop on the setting. But still doesnt work. But thanks for your answer and solution.
