### ISSUE TITLE
Flutter web is possible ?

### ISSUE THREAD

**Issue by gedw99** [felixjunghans/google_speech#11]
very awesome project. 

I would like to try to do speech to text subtitles for Webrtc video conference over the web.

The sound package supports web.
https://github.com/Canardoux/tau

- this one has many pr#s that are ahead of the https://github.com/dooboolab/flutter_sound origin

 iOS and Safari is not possible because Apple block it. Same with webrtc video and audio capture - no idea why they block it but that’s apple.

grpc works very well with grpc web so it will be easy to call the google service over grpc i think. I use it a fair bit. Hve not tested it yet though, but i expect it will be fine.

Are there any other blockers that you know of ?

**Comment by felixjunghans** [comment]
I will try to support web soon.

**Comment by felixjunghans** [comment]
See #20
