### ISSUE TITLE
Google_speech is not compatible with Flutter 2.0.1

### ISSUE THREAD

**Issue by alariad** [felixjunghans/google_speech#14]
**Describe the bug**
Google_speech is not compatible with Flutter 2.0.1 and is throwing errors.

Because no versions of firebase_messaging match >9.0.0 <10.0.0 and firebase_messaging 9.0.0 depends on firebase_core_platform_interface ^4.0.0, firebase_messaging ^9.0.0 requires firebase_core_platform_interface ^4.0.0.
And because no versions of firebase_core_platform_interface match >4.0.0 <5.0.0 and firebase_core_platform_interface 4.0.0 depends on plugin_platform_interface ^2.0.0, firebase_messaging ^9.0.0 requires plugin_platform_interface ^2.0.0.
And because path_provider >=1.6.4 <2.0.0-nullsafety depends on path_provider_platform_interface ^1.0.1 which depends on plugin_platform_interface ^1.0.1, firebase_messaging ^9.0.0 is incompatible with path_provider >=1.6.4 <2.0.0-nullsafety.
Because google_speech <1.1.0 depends on path_provider ^1.6.8 and google_speech >=1.1.0 depends on path_provider ^1.6.11, every version of google_speech requires path_provider ^1.6.8.
Thus, firebase_messaging ^9.0.0 is incompatible with google_speech.
So, because flutter_app depends on both firebase_messaging ^9.0.0 and google_speech any, version solving failed.
pub get failed (1; So, because flutter_app depends on both firebase_messaging ^9.0.0 and google_speech any, version solving failed.)

**Comment by felixjunghans** [comment]
Hi, Sorry for the late reply. I have just released a new version (2.0.0) that is compatible with Flutter 2.2.0.
