### ISSUE TITLE
Support for Flutter Web

### ISSUE THREAD

**Issue by menezes85** [felixjunghans/google_speech#17]
Hello Felix, Thanks for this awesome package,  is there any way to support flutter web?

**Comment by felixjunghans** [comment]
Yes I have planned to support Flutter Web and in principle there is nothing against it, but the GRPC package does not support Web. I have recently seen that there is a GRPC package for web and have it on the roadmap to include this.

**Comment by alaincruz06** [comment]
Hi @felixjunghans is this a priority or at least a TODO on your schedule actually?
I know there's been some time since you published the package.

**Comment by felixjunghans** [comment]
Hi we have already tried to make this package available for Flutter Web. Unfortunately this is not really practical at the moment as you can see here #20 . For Flutter Web I currently recommend the use of the Google Api Package.
