### ISSUE TITLE
Example of Mic Stream using flutter sound

### ISSUE THREAD

**Issue by menezes85** [felixjunghans/google_speech#18]
Felix , thanks for  your work!

Can you please provide me an example  how to implement google_speech using mic stream with flutter_sound ? 
[https://pub.dev/packages/flutter_sound]

i am hangang on that , over 1 month and no success. stream types provided by flutter sound and google_speech are different i cant do it. 

Thanks in advance.

**Comment by sveinbjornt** [comment]
@menezes85 I've solved this particular problem, if you send me an email, I can send you some sample code (still not open on GH). My email is sveinbjorn at sveinbjorn, dot org.

**Comment by bosscoekku** [comment]
@felixjunghans I also would like to implement with Flutter Sound. Thank you so much.

**Comment by RishiKar** [comment]
@felixjunghans thank you for your package. Did you get around to implementing this with Flutter Sound?
I am also stuck on passing the stream to streamingRecognize when using Flutter Sound.
Is any other package better suited, any help would be welcome

**Comment by felixjunghans** [comment]
@RishiKar Yes, I currently use it with flutter_sound_lite. I have now added a minimal example. Please have a look at examples/flutter_sound_example. I hope this helps you.

**Comment by RishiKar** [comment]
@felixjunghans Thank you so much. I got it to work. Now I am running into issues with flutter sound for using bluetooth devices for recording and playback 🥲 but otherwise it does work.
