### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by ninjaasmoke** [felixjunghans/google_speech#2]
Google speech to text supports detection of languages automatically while speaking. Can this feature be implemented?

**Comment by felixjunghans** [comment]
Hi @ninjaasmoke , as far as I can see, the automatic language detection is only a beta feature so far. This package currently accesses the V1 stable version. But I will try to support the beta functions with the next update. I will do my best to release a new version this week.

**Comment by ninjaasmoke** [comment]
That'd be amazing, appreciate it

**Comment by felixjunghans** [comment]
@ninjaasmoke google_speech now (version 1.1.0) supports the Google Speech Beta Api. Instead of SpeechToText just use SpeechToTextBeta. Then you have the possibility to specify alternative languages in the config besides a language. Google will then use the language that is most likely.

**Comment by ninjaasmoke** [comment]
Amazing! Thanks
