### ISSUE TITLE
[suggestion] please support google cloud text to speech

### ISSUE THREAD

**Issue by premingiet** [felixjunghans/google_speech#21]
**Is your feature request related to a problem? Please describe.**
There is no flutter plugin i can find which supports google cloud text to speech. Only one plugin is there but doesn't support cloud functionality

**Describe the solution you'd like**
support google cloud text to speech

**Comment by felixjunghans** [comment]
Hello this plugin is only meant to support speech to text. There is currently no capacity to add this functionality. Sorry
