### ISSUE TITLE
Getting empty response

### ISSUE THREAD

**Issue by ajinkya446** [felixjunghans/google_speech#25]
**Actual bug**
Getting empty response from the speech recognition.

**Description**
After recording audio file using recorder package then after playing audio file i wanted to transcribe the audio content but when i transcribing the audio file to text then getting empty response.

**Smartphone**
 - Device: Samsung M31, Samsung j7 nxt
 - OS: Android sdk 30, Android sdk 29

**Comment by felixjunghans** [comment]
Hi, I have just updated the audio file example. Please have a look at it. There the recognition of an audio file works without problems.

[Audio File Example](https://github.com/felixjunghans/google_speech/tree/master/example/audio_file_example)

Feel free to reopen this issue if you have any further questions

**Comment by ajinkya446** [comment]
@felixjunghans This google_speech package working fine and transcribing audio perfectly but the issue is with the recorder file. The recorded audio file does not contain any  LINEAR16 encoding must be 16-bits and also, sample rate of audio file is not 16000. When i check metadata of that file it says that audio file contains 44100 sample rate. 

**

> Note: Your package sending empty response because of that improper audio file metadata and i tried with other file as well and it is transcribing correctly. Kindly take a look on the google cloud speech to text documentation below for transcribing audio.

**

https://cloud.google.com/speech-to-text/docs/troubleshooting#returns_an_empty_response

**Kindly add this into the readme file also for more who are facing the same issue.**

**Comment by felixjunghans** [comment]
Thank you for your reply. I will add the hint in the README.
