### ISSUE TITLE
Mic Stream - Google speech not working

### ISSUE THREAD

**Issue by kelrigor** [felixjunghans/google_speech#28]
Hi anyone can helpme, 

I'm trying google speech - Mic Stream in flutter, i've already implement the service account and initialized but when i run the application my voice/speech did not recoginized. 

thanks

**Comment by felixjunghans** [comment]
Hi, did you check if input is coming from your microphone and that you set the sampleRateHertz correctly?

**Comment by kelrigor** [comment]
Hi,

Already solved the problem, found that the issue is sound stream.

Thanks
