### ISSUE TITLE
longRunningRecognize result

### ISSUE THREAD

**Issue by hcihan** [felixjunghans/google_speech#31]
how do i get a text file with longRunningRecognize. it's just returned name text.
name: 5279715233814577284
![Ekran Resmi 2023-03-06 16 27 14](https://user-images.githubusercontent.com/46005238/223123295-f1816a41-344f-403d-897e-730c331021b3.png)

**Comment by felixjunghans** [comment]
I don't know if I understand you correctly, but you can write the response yourself in a text file and save it?

**Comment by hcihan** [comment]
`final responseLongRunning = await speechToText
        .longRunningRecognize(
        RecognitionConfig(
          audioChannelCount: 2,
          encoding: AudioEncoding.LINEAR16,
          model: RecognitionModel.basic,
          enableAutomaticPunctuation: true,
          sampleRateHertz: 44100,
          languageCode: 'tr-TR',
          useEnhanced: false,
        ),
        'gs://hyunda/kisa.m4a');
  }`
This is my LongRunningRecognize function.
My result is just that
name:"";

**Comment by felixjunghans** [comment]
Info in #44
