### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by akhilgorantala** [felixjunghans/google_speech#32]
e: C:\Users\AKHIL\AppData\Local\Pub\Cache\hosted\pub.dev\sound_stream-0.3.0\android\src\main\kotlin\vn\casperpas\sound_stream\SoundStreamPlugin.kt: (45, 8): Class 'SoundStreamPlugin' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: C:\Users\AKHIL\AppData\Local\Pub\Cache\hosted\pub.dev\sound_stream-0.3.0\android\src\main\kotlin\vn\casperpas\sound_stream\SoundStreamPlugin.kt: (182, 5): 'onRequestPermissionsResult' overrides nothing

**Comment by felixjunghans** [comment]
Can you please provide more information? It doesn't look like this error is related to this package but to https://pub.dev/packages/sound_stream
