### ISSUE TITLE
Stop Recording crashed the app

### ISSUE THREAD

**Issue by akhilg-9** [felixjunghans/google_speech#34]
D/AudioRecord(16342): stop(1056): mActive:1
D/AudioRecord(16342): call mAudioRecord->stop()
D/AudioRecord(16342): call AudioRecordThread pause()
D/AudioRecordExtImpl(16342): clearAudioBoostTid
D/AudioRecordExtImpl(16342): clearAudioBoostTid  pid 16342  tid 16342
D/AudioRecordExtImpl(16342): clearAudioBoostTid  pid 16342  tid 21189
D/AudioRecord(16342): stop(1056) done
I/Quality (16342): Skipped: false 5 cost 84.65327 refreshRate 16586000 bit true processName com.example.untitled4
E/AudioRecord-JNI(16342): Error -38 during AudioRecord native read
D/AndroidRuntime(16342): Shutting down VM
E/AndroidRuntime(16342): FATAL EXCEPTION: main
E/AndroidRuntime(16342): Process: com.example.untitled4, PID: 16342
E/AndroidRuntime(16342): java.lang.IllegalArgumentException
E/AndroidRuntime(16342): 	at java.nio.ByteBuffer.allocate(ByteBuffer.java:283)
E/AndroidRuntime(16342): 	at vn.casperpas.sound_stream.SoundStreamPlugin$createRecordListener$1.onPeriodicNotification(SoundStreamPlugin.kt:390)
E/AndroidRuntime(16342): 	at android.media.AudioRecord$NativeEventHandler.handleMessage(AudioRecord.java:2313)
E/AndroidRuntime(16342): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16342): 	at android.os.Looper.loopOnce(Looper.java:240)
E/AndroidRuntime(16342): 	at android.os.Looper.loop(Looper.java:351)
E/AndroidRuntime(16342): 	at android.app.ActivityThread.main(ActivityThread.java:8364)
E/AndroidRuntime(16342): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16342): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(16342): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
I/Process (16342): Sending signal. PID: 16342 SIG: 9
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"130","method":"getMemoryUsage","params":{"isolateId":"isolates/76716778165859"}}

**Comment by felixjunghans** [comment]
Looks like the SoundStream plugin is the reason. Are you working with the Example app?

**Comment by felixjunghans** [comment]
Ok, thanks. I'll look into it.
