### ISSUE TITLE
Flutter Web Support

### ISSUE THREAD

**Issue by pelaezcarlos** [felixjunghans/google_speech#38]
Do you have support for Flutter Web in the Beta version?
Or do you have a probable date for this integration?

**Comment by felixjunghans** [comment]
Hi. Currently google_speech does not support web. This is because grpc is not designed for flutter web. If it helps you you can use the google apis package instead, which also supports flutter web.

**Comment by pelaezcarlos** [comment]
Thanks for your answer.
With Google APIs can I do cross-platform Speech integration in flutter? web/Android/IOS/Mac/windows

**Comment by felixjunghans** [comment]
The package https://pub.dev/packages/googleapis is available for all Platforms. The only thing you can't do is streaming speech to text
