### ISSUE TITLE
Support for google.cloud.speech.v2

### ISSUE THREAD

**Issue by bilalahmed24** [felixjunghans/google_speech#43]
**Is your feature request related to a problem? Please describe.**
The current google_speech package in Flutter supports Google Speech v1, but I need support for Google Speech v2 due to its improved accuracy and features.

**Describe the solution you'd like**
'm requesting an upgrade to the google_speech package to support Google Speech v2, enabling developers to leverage its benefits while maintaining package integration.

**Additional context**
Supporting Google Speech v2 would enhance speech recognition accuracy and capabilities, benefiting a wide range of Flutter applications, including accessibility features and voice assistants.

**Comment by felixjunghans** [comment]
Hey @bilalahmed24.

Thank you for your suggestion. I will check which adjustments are necessary for this. Unfortunately, I will not have time for this until next week.

**Comment by bilalahmed24** [comment]
@felixjunghans Thanks for your prompt response and for this great package, I can surely wait for another week :)

**Comment by bilalahmed24** [comment]
@felixjunghans Any update?

**Comment by felixjunghans** [comment]
Hey @bilalahmed24, sorry for the Delay.

Yesterday I regenerated all proto APIs for version 2 and made the necessary adjustments. However, a few things still didn't work as expected.

I plan to update google_Speech on Pub with the Google Speech version 2 Support this weekend.

**Comment by bilalahmed24** [comment]
@felixjunghans Great to hear that, I'm looking forward to it.

**Comment by felixjunghans** [comment]
Hey @bilalahmed24  google_speech 4.0.0 now Supports V2 Api. I also added a new example (audio_file_v2) because the api is a little bit different. Please test it and if you find any bugs or missing features, feel free to open a new issue or reopen this issue. 

Hope that helps

**Comment by bilalahmed24** [comment]
@felixjunghans There seems to be some null check issue.

W/Parcel  ( 5350): Expecting binder but got null!
E/flutter ( 5350): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 5350): #0      new SpeechToTextV2.viaServiceAccount        speech_to_text_v2.dart:35

**Comment by felixjunghans** [comment]
Do you have a project_id set in your ServiceAccount.json?

**Comment by bilalahmed24** [comment]
@felixjunghans Thanks, I got that working. 
But now I am facing issue with streamingRecognize which immediately throws error as audio data is passed through the stream. The same serviceAccount.json is working fine with v1.


GrpcError (gRPC Error (code: 7, codeName: PERMISSION_DENIED, message: Permission 'speech.recognizers.recognize' denied on resource (or it may not exist)., details: [reason: IAM_PERMISSION_DENIED]
message: "Permission 'speech.recognizers.recognize' denied on resource (or it may not exist)."

**Comment by bilalahmed24** [comment]
@felixjunghans Let me get back to you with audio_example_v2 result.

**Comment by bilalahmed24** [comment]
@felixjunghans Same error with audio_example_v2 provided code, with both streamingRecognize and recognize. 
That's intriguing, is recognize using gRPC as well instead of restAPI?

**Comment by felixjunghans** [comment]
Ok. Yes everything in google_speech uses gRPC. It looks like you need some IAM permissions since Google Speech V2 according to this doc https://cloud.google.com/speech-to-text/v2/docs/reference/rpc/google.cloud.speech.v2#google.cloud.speech.v2.Speech.StreamingRecognize  

Could you try to add these permissions to your service account?

**Comment by bilalahmed24** [comment]
@felixjunghans Thanks for the help you were right regarding the permissions. 

Streaming request is abruptly being closed due to two errors, sometimes it's "stream timeout" or "the operation was cancelled".
I am using microphone to pass audio to stream req.
I wasn't facing this using v1. Could it be due to some v2 streaming request restriction?

**Comment by felixjunghans** [comment]
@bilalahmed24 Unfortunately, I can't say much about it, since I've only used version 2 for testing purposes so far. The only thing I noticed is that since version 2 the chunkLength for StreamingRecognize is limited to 25600 bytes per request.

If you find out more or think a bug in google_speech is causing this, I'll be happy to fix it. But so far I don't know where the bug should be.

**Comment by bilalahmed24** [comment]
@felixjunghans Okay, I will let you know if I bump into any bug.

Thanks for the help. :)
