### ISSUE TITLE
Support for SpeechContexts in RecognitionConfig

### ISSUE THREAD

**Issue by mdeloge** [felixjunghans/google_speech#5]
Currently there in no support for SpeechContexts in the RecognitionConfig class for streaming recognition. We have a client that will be needing this support in the near future and as such I'm wondering if there is any timeline available regarding this feature, if any.

The ideal solution for us would to be able to set the speech contexts as defined in the Google Speech-to-Text documentation: https://cloud.google.com/speech-to-text/docs/reference/rest/v1/RecognitionConfig 

Thanks in advance for the update.

**Comment by felixjunghans** [comment]
Hi, I have just released a new version (1.2.0) which also supports SpeechContexts. If you need help with using it, please let me know.

**Comment by mdeloge** [comment]
Thanks for the quick solution! Seems to be working like a charm :+1:
