### ISSUE TITLE
code: 1, codeName: CANCELLED

### ISSUE THREAD

**Issue by NSLogZfRee** [felixjunghans/google_speech#52]
In an RTC live broadcast scenario, there's an error when the microphone callback is used for Google ASR recognition.

When streamingRecognize starts for a while, got this  error:
I/flutter ( 7773): gRPC Error (code: 1, codeName: CANCELLED, message: The operation was cancelled., details: [], rawResponse: null, trailers: {}) GrpcError

flutter  3.16.0
google_speech: ^4.4.0

**Comment by NSLogZfRee** [comment]
![Uploading 截屏2024-01-16 21.12.21.png…]()

**Comment by NSLogZfRee** [comment]
@
<img width="945" alt="截屏2024-01-16 21 13 34" src="https://github.com/felixjunghans/google_speech/assets/34330456/f7823a58-0157-4f62-be64-3634e2811c73">

**Comment by NSLogZfRee** [comment]
<img width="706" alt="截屏2024-01-16 21 12 21" src="https://github.com/felixjunghans/google_speech/assets/34330456/c138feb9-fad2-4108-b1b8-8392a2f91635">

**Comment by felixjunghans** [comment]
@NSLogZfRee I have just released version 5.0.0 with endless streaming support. Please test if this solves your problem.
