### ISSUE TITLE
Support configuration of service region

### ISSUE THREAD

**Issue by simonbrandhof** [felixjunghans/google_speech#53]
The Google Speech API provides the capability to [select the service region](https://cloud.google.com/speech-to-text/docs/endpoints) when sending requests (US or Europe). That can be important for the compliance with local regulatory requirements, and probably for better performances for nearby users.

Currently the global endpoint `speech.googleapis.com` is hardcoded in the `SpeechToText` class and can't be changed. It would be great to add the support for its configuration, for example by using an enum:

```dart
SpeechToText.viaServiceAccount(serviceAccount, region: Region.europe);
```

**Comment by felixjunghans** [comment]
Hey @simonbrandhof, 

Thank you for your feedback. I have just released version 5.1.0. 
It is now possible to use regional endpoints with the optional parameter 'cloudSpeechEndpoint'. I hope this helps you.

`SpeechToText.viaServiceAccount(serviceAccount, cloudSpeechEndpoint: 'https://eu-speech.googleapis.com');`

**Comment by simonbrandhof** [comment]
Excellent, kudos to you 👍

**Comment by simonbrandhof** [comment]
Note that the parameter `cloudSpeechEndpoint` is the host, but not the URL. The correct example is:
```
SpeechToText.viaServiceAccount(serviceAccount, cloudSpeechEndpoint: 'eu-speech.googleapis.com');
```

**Comment by felixjunghans** [comment]
Ahh, you're right. Thanks for the correction.
