### ISSUE TITLE
[SpeechToTextV2] Setting cloudSpeechEndpoint doesn't update resource location

### ISSUE THREAD

**Issue by bilalahmed24** [felixjunghans/google_speech#56]
**Describe the bug**
I was trying to use chirp model with v2 using 'pollingLongRunningRecognize' and had to provide the 'cloudSpeechEndpoint' since Chirp is only available on specific regions. The issue is recognizer path doesn't update the location it's hardcoded to be 'global'.
Moreover, as shown in the image below if I change the location to wrt to 'cloudSpeechEndpoint', no results are return by google.

**Expected behavior**
The location should update with respect to cloudSpeechEndpoint.
recognizer: 'projects/$projectId/locations/{{location}}/recognizers/_', ✅

recognizer: 'projects/$projectId/locations/global/recognizers/_',  ❎ 

**Screenshots**
![image](https://github.com/felixjunghans/google_speech/assets/64329544/14368a48-c906-47bd-a931-ff3a68773dc1)

**Additional Context**
https://cloud.google.com/speech-to-text/v2/docs/chirp-model#perform_synchronous_speech_recognition_with_chirp

**Comment by felixjunghans** [comment]
Thanks for reporting @bilalahmed24 . With version 5.2.0 it is now possible to set the location.

```
  Future<LongRunningRequestResult> pollingLongRunningRecognize(
      RecognitionConfigV2 config, String audioGcsUri,
      {Duration pollInterval = const Duration(seconds: 1), String location = 'global'}) async {
```
