### ISSUE TITLE
longRunningRecognize support

### ISSUE THREAD

**Issue by SonQBChau** [felixjunghans/google_speech#6]
I have a project that is suitable for longRunningRecognize, for example, transcribe the whole class lesson. 

How difficult is it to add this feature?  I think streaming will work for my purpose but I wonder if I can use longRunningRecognize in the future.

**Comment by felixjunghans** [comment]
Since I wanted to complete the package bit by bit, this feature is of course on my list. Now that there is a real use for it, I will try to include this feature next. I can't estimate how long it will take, though.

**Comment by menezes85** [comment]
Thats a real need too felix

**Comment by spenceralbrecht** [comment]
I could really use the longRunningRecognize for a project I am working on as well. It would be great if you could add it @felixjunghans.

**Comment by spenceralbrecht** [comment]
I'm hoping #26 is all that's needed to get this working.

**Comment by felixjunghans** [comment]
Thanks @spenceralbrecht for your work. I released a new version (v.2.1.0) with longRunningRecognize support

**Comment by spenceralbrecht** [comment]
> Thanks @spenceralbrecht for your work. I released a new version (v.2.1.0) with longRunningRecognize support

Thank you! 💪

**Comment by RishiKar** [comment]
@felixjunghans amazing job at checking off the roadmap items 💪
thanks to @spenceralbrecht too 
I wanted to try out the longRunningRecognize feature and I am getting a bit stuck on reading the results of the transcription.
```
 final responseLongRunning = await speechToText
        .longRunningRecognize(
            RecognitionConfigBeta(
              encoding: AudioEncoding.LINEAR16,
              model: RecognitionModel.basic,
              enableAutomaticPunctuation: true,
              sampleRateHertz: 16000,
              languageCode: 'en-US',
              useEnhanced: false,
            ),
            'gs://testFile/New Recording 6.m4a')
```

now this essentially returns an operation. and I can get the name of the operation by 
`responseLongRunning.name`

but is it now expected to make a get request using this name or is there a more obvious way of accessing the alternatives.first.transcript value ?

**Comment by spenceralbrecht** [comment]
> @felixjunghans amazing job at checking off the roadmap items 💪 thanks to @spenceralbrecht too I wanted to try out the longRunningRecognize feature and I am getting a bit stuck on reading the results of the transcription.
> 
> ```
>  final responseLongRunning = await speechToText
>         .longRunningRecognize(
>             RecognitionConfigBeta(
>               encoding: AudioEncoding.LINEAR16,
>               model: RecognitionModel.basic,
>               enableAutomaticPunctuation: true,
>               sampleRateHertz: 16000,
>               languageCode: 'en-US',
>               useEnhanced: false,
>             ),
>             'gs://testFile/New Recording 6.m4a')
> ```
> 
> now this essentially returns an operation. and I can get the name of the operation by `responseLongRunning.name`
> 
> but is it now expected to make a get request using this name or is there a more obvious way of accessing the alternatives.first.transcript value ?

Your request willl return an operation object that will have a property "done" which you will need to check in order to access the "response" property of the operation properly. See https://pub.dev/documentation/google_speech/latest/generated_google_longrunning_operations.pb/Operation-class.html.
