### ISSUE TITLE
Support Google user login

### ISSUE THREAD

**Issue by ffeldhaus** [felixjunghans/google_speech#8]
Storing a service account key inside the App can pose a serious security issue, as anyone with access to the app has access to all resources in the Google Cloud Project, especially as Speech-to-Text requires a role granting access to all project resources!
A good starting point could be https://pub.dev/packages/google_sign_in

**Comment by felixjunghans** [comment]
Thanks for your request. I will try to support it soon.

**Comment by gedw99** [comment]
the easier way is to just grab te key from your server the call to get the key can require a key, which you authentication on your server.

then the key is returned to flutter into memory.
you can then if you so choose store the key in the key store. see: https://github.com/mogol/flutter_secure_storage

**Comment by ffeldhaus** [comment]
@gedw99 That's a good suggestion, but I think it's a separate feature request. Using service account keys require some other authentication method to guard access to the service account key, even if you are using your proposed solution (unless you want to have unrestricted access to the service account key by everyone). Using Google user login, no server based authentication is required - e.g. I can just put a Flutter Web App on Cloud Storage and run it from there with authentication handled by Google.

**Comment by gedw99** [comment]
i dont get it.

the key eventually has to be given to the client. 

your just making access to the flutter source code behind an authentication guard.

i dont see this solving the actual problem.

**Comment by ffeldhaus** [comment]
What I suggest is to add a new feature to not use any service account keys inside the Flutter App but use Google user login. This is described in detail in [Using OAuth 2.0 to Access Google APIs](https://developers.google.com/identity/protocols/oauth2 ). Currently google_speech uses the [scenario Service accounts](https://developers.google.com/identity/protocols/oauth2#serviceaccount) and I am suggesting here to also support one of the other scenarios where the user authenticates (e.g. usually with Email and Password or MFA). In both cases, an OAuth 2.0 access token is generated which is used by google_speech to authenticate against the Speech-to-Text API.

**Comment by juarezfranco** [comment]
Is it possible login with server with google account service (json) and send bearer token to client (app mobile)?

**Comment by felixjunghans** [comment]
Maybe I can find a solution where you can pass the AccessCredentials from google_sign_in to google_speech. I'll will take a look in the next few days.

**Comment by juarezfranco** [comment]
> Is it possible to log in to the server using the Google account service (json) and send a bearer token to the client (mobile app)?

I added support for external authentication to the application. #42

**Comment by felixjunghans** [comment]
Hey @juarezfranco, thank you very much. I will look at it right away and then merge and provide a new version.

**Comment by felixjunghans** [comment]
Big Thanks again to @juarezfranco. This is now possible with google_speech 3.0.0.
